# ------------------- Controller Manager CSRCleaner Role Binding (Temporary - Fixed in Kubernetes #59375) ------------------- #
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubo:internal:csr-delete
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubo:internal:csr-delete
subjects:
- kind: ServiceAccount
  name: certificate-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubo:internal:csr-delete
  apiGroup: rbac.authorization.k8s.io
